In [1]:
import pandas as pd
import glob

In [10]:
csvlist = glob.glob('*.csv')

df_scopus = pd.DataFrame()

length = 0

for file in csvlist:
    data = pd.read_csv(file)
    length += len(data)

    df_scopus = pd.concat([df_scopus, data], axis=0)

In [29]:
length

437

In [11]:
df_scopus.columns

Index(['Authors', 'Author full names', 'Author(s) ID', 'Title', 'Year',
       'Source title', 'Volume', 'Issue', 'Art. No.', 'Page start', 'Page end',
       'Cited by', 'DOI', 'Link', 'Affiliations', 'Authors with affiliations',
       'Abstract', 'Author Keywords', 'Index Keywords',
       'Molecular Sequence Numbers', 'Chemicals/CAS', 'Tradenames',
       'Manufacturers', 'Funding Details', 'Funding Texts', 'References',
       'Correspondence Address', 'Editors', 'Publisher', 'Sponsors',
       'Conference name', 'Conference date', 'Conference location',
       'Conference code', 'ISSN', 'ISBN', 'CODEN', 'PubMed ID',
       'Language of Original Document', 'Abbreviated Source Title',
       'Document Type', 'Publication Stage', 'Open Access', 'Source', 'EID'],
      dtype='object')

In [ ]:
#further_filter = df_scopus[['Title', 'Document Type']]

In [21]:
further_filter = df_scopus[df_scopus['Document Type'] == 'Article']

In [31]:
df_scopus = df_scopus[['Title', 'Source', 'Link', 'Abstract']]

In [32]:
df_scopus

,Title,Source,Link,Abstract
0,Algorithmic Climate Justice: How AI Bias Exace...,Scopus,https://www.scopus.com/pages/publications/1050...,This chapter explores how algorithmic biases i...
1,"Automation, AI, and the Global Future of Work:...",Scopus,https://www.scopus.com/pages/publications/1050...,Automation and artificial intelligence (AI) ar...
2,Coding and Capability-Building in Nonprofit Di...,Scopus,https://www.scopus.com/pages/publications/8519...,Digital journalism scholars highlighted a gap ...
3,Intelligent Future or Neo-colonialism?,Scopus,https://www.scopus.com/pages/publications/1050...,This is a commentary on the current fervour ab...
4,Flood-tech frontiers: smart but just? A system...,Scopus,https://www.scopus.com/pages/publications/1050...,"As rising waters meet rising technologies, a n..."
...,...,...,...,...
1,A global geospatial analysis to evaluate the i...,Scopus,https://www.scopus.com/pages/publications/8521...,The effectiveness of biochar as a soil amendme...
2,GRAIN – a Global Registry of Agricultural Irri...,Scopus,https://www.scopus.com/pages/publications/1050...,Despite supporting roughly 40 % of the world's...
3,Benthic Peracarids (Crustacea) from an unexplo...,Scopus,https://www.scopus.com/pages/publications/8509...,Background The intricate geomorphology of the ...
4,Evolutionary dynamics and global diversity of ...,Scopus,https://www.scopus.com/pages/publications/8494...,The increasing number of zoonotic infections c...
5,Wildfire burn severity in the mediterranean bi...,Scopus,https://www.scopus.com/pages/publications/1050...,Wildfire burn severity serves as a key metric ...

In [33]:
xlsllist = glob.glob('*.xls')

In [16]:
xlsllist = glob.glob('*.xls')

df_wob = pd.DataFrame()

length = 0

for file in xlsllist:
    data = pd.read_excel(file)
    length += len(data)

    df_wob = pd.concat([df_wob, data], axis=0)

In [17]:
df_wob.columns

Index(['Publication Type', 'Authors', 'Book Authors', 'Book Editors',
       'Book Group Authors', 'Author Full Names', 'Book Author Full Names',
       'Group Authors', 'Article Title', 'Source Title', 'Book Series Title',
       'Book Series Subtitle', 'Language', 'Document Type', 'Conference Title',
       'Conference Date', 'Conference Location', 'Conference Sponsor',
       'Conference Host', 'Author Keywords', 'Keywords Plus', 'Abstract',
       'Addresses', 'Affiliations', 'Reprint Addresses', 'Email Addresses',
       'Researcher Ids', 'ORCIDs', 'Funding Orgs', 'Funding Name Preferred',
       'Funding Text', 'Cited References', 'Cited Reference Count',
       'Times Cited, WoS Core', 'Times Cited, All Databases',
       '180 Day Usage Count', 'Since 2013 Usage Count', 'Publisher',
       'Publisher City', 'Publisher Address', 'ISSN', 'eISSN', 'ISBN',
       'Journal Abbreviation', 'Journal ISO Abbreviation', 'Publication Date',
       'Publication Year', 'Volume', 'Issue', 'Part Number', 'Supplement',
       'Special Issue', 'Meeting Abstract', 'Start Page', 'End Page',
       'Article Number', 'DOI', 'DOI Link', 'Book DOI', 'Early Access Date',
       'Number of Pages', 'WoS Categories', 'Web of Science Index',
       'Research Areas', 'IDS Number', 'Pubmed Id', 'Open Access Designations',
       'Highly Cited Status', 'Hot Paper Status', 'Date of Export',
       'UT (Unique WOS ID)', 'Web of Science Record'],
      dtype='object')

In [20]:
df_wob_type = df_wob[['Article Title','Document Type']]

In [ ]:
df_wob[df_wob['Document Type'] == 'Article']

In [36]:
df_wob['Source'] = 'WoB'

In [37]:
df_wob = df_wob[['Article Title', 'Source', 'Abstract']]

In [38]:
df_wob = df_wob.rename(columns={'Article Title': 'Title'})

In [39]:
df_wob

,Title,Source,Abstract
0,A global geospatial analysis to evaluate the i...,WoB,The effectiveness of biochar as a soil amendme...
1,Geospatial Big Data or Big Geospatial Data: A ...,WoB,The study reviews a broad body of published li...
2,Remote Sensing and Geospatial Analysis in the ...,WoB,The present survey examines the role of big da...
3,Advancing geospatial methods for addressing gl...,WoB,Rising demands on global resources and ecosyst...
4,"STAC, an open n standard to o describe and cat...",WoB,The STAC is a recent geospatial standard that ...
...,...,...,...
120,"GIS, spatial analysis and spatial statistics",WoB,NaN
121,Measuring Equity through Spatial Variability o...,WoB,Recent regional research has taken an 'infrast...
122,GIS and Spatial Statistics/Econometrics: An Ov...,WoB,NaN
123,Spatial Variations in US Poverty: Beyond Metro...,WoB,Because poverty in rural and urban areas of th...
124,Spatial Determinants of Poverty Using GIS-Base...,WoB,NaN

In [32]:
google_sch = pd.read_excel('Google_scholars.xlsx')

In [41]:
google_sch['Source'] = 'Google Scholar'

In [42]:
google_sch = google_sch[['Title', 'Source', 'link']]

In [43]:
google_sch = google_sch.rename(columns={'link':'Link'})

In [44]:
google_sch

,Title,Source,Link
0,Assessing the completeness and positional accu...,Google Scholar,https://link.springer.com/chapter/10.1007/978-...
1,An automated method to assess data completenes...,Google Scholar,https://www.geocomputation.org/2011/papers/kou...
2,A new method for the assessment of spatial acc...,Google Scholar,https://www.mdpi.com/2220-9964/7/8/289
3,Exploring the accuracy and completeness patter...,Google Scholar,https://www.sciencedirect.com/science/article/...
4,Mapping the completeness and positional accura...,Google Scholar,https://onlinelibrary.wiley.com/doi/abs/10.111...
...,...,...,...
173,A cross-sectional ecological analysis of inter...,Google Scholar,https://link.springer.com/article/10.1186/s129...
174,Understanding needs and barriers to using geos...,Google Scholar,https://utd-ir.tdl.org/items/12a73918-3023-445...
175,The cost (s) of geospatial open data,Google Scholar,https://onlinelibrary.wiley.com/doi/abs/10.111...
176,Community geography: Addressing barriers in pu...,Google Scholar,https://www.tandfonline.com/doi/abs/10.1080/00...
177,Identifying and overcoming the barriers to pri...,Google Scholar,https://repository.tudelft.nl/file/File_e598dc...

In [45]:
all_data = pd.concat([df_scopus, google_sch, df_wob], axis=0)

In [46]:
all_data

,Title,Source,Link,Abstract
0,Algorithmic Climate Justice: How AI Bias Exace...,Scopus,https://www.scopus.com/pages/publications/1050...,This chapter explores how algorithmic biases i...
1,"Automation, AI, and the Global Future of Work:...",Scopus,https://www.scopus.com/pages/publications/1050...,Automation and artificial intelligence (AI) ar...
2,Coding and Capability-Building in Nonprofit Di...,Scopus,https://www.scopus.com/pages/publications/8519...,Digital journalism scholars highlighted a gap ...
3,Intelligent Future or Neo-colonialism?,Scopus,https://www.scopus.com/pages/publications/1050...,This is a commentary on the current fervour ab...
4,Flood-tech frontiers: smart but just? A system...,Scopus,https://www.scopus.com/pages/publications/1050...,"As rising waters meet rising technologies, a n..."
...,...,...,...,...
120,"GIS, spatial analysis and spatial statistics",WoB,NaN,NaN
121,Measuring Equity through Spatial Variability o...,WoB,NaN,Recent regional research has taken an 'infrast...
122,GIS and Spatial Statistics/Econometrics: An Ov...,WoB,NaN,NaN
123,Spatial Variations in US Poverty: Beyond Metro...,WoB,NaN,Because poverty in rural and urban areas of th...
124,Spatial Determinants of Poverty Using GIS-Base...,WoB,NaN,NaN

In [47]:
all_data['Title'] = all_data['Title'].astype(str).str.lower()

In [ ]:
#all_data.to_csv('combined_data.csv', index=False)

In [ ]:
#all_data = all_data[~all_data.duplicated(subset='Title')]

In [ ]:
#all_data

                                                 Title          Source
0    flood-tech frontiers: smart but just? a system...          Scopus
46   quality evaluation of volunteered geographic i...          Scopus
62   exploiting multiple heterogeneous data sets fo...          Scopus
5                                       digital divide          Scopus
6        a review of literature on information poverty          Scopus
..                                                 ...             ...
148          spatial inequalities and cities: a review  Google Scholar
149  urban disparity analytics using gis: a systema...  Google Scholar
154  nutritional inequalities among under-five chil...  Google Scholar
161  geospatial data sharing barriers across organi...  Google Scholar
168                    barriers to gis use in planning  Google Scholar

[289 rows x 2 columns]

In [48]:
dropduplicat = all_data.drop_duplicates(subset='Title')

In [49]:
dropduplicat

,Title,Source,Link,Abstract
0,algorithmic climate justice: how ai bias exace...,Scopus,https://www.scopus.com/pages/publications/1050...,This chapter explores how algorithmic biases i...
1,"automation, ai, and the global future of work:...",Scopus,https://www.scopus.com/pages/publications/1050...,Automation and artificial intelligence (AI) ar...
2,coding and capability-building in nonprofit di...,Scopus,https://www.scopus.com/pages/publications/8519...,Digital journalism scholars highlighted a gap ...
3,intelligent future or neo-colonialism?,Scopus,https://www.scopus.com/pages/publications/1050...,This is a commentary on the current fervour ab...
4,flood-tech frontiers: smart but just? a system...,Scopus,https://www.scopus.com/pages/publications/1050...,"As rising waters meet rising technologies, a n..."
...,...,...,...,...
120,"gis, spatial analysis and spatial statistics",WoB,NaN,NaN
121,measuring equity through spatial variability o...,WoB,NaN,Recent regional research has taken an 'infrast...
122,gis and spatial statistics/econometrics: an ov...,WoB,NaN,NaN
123,spatial variations in us poverty: beyond metro...,WoB,NaN,Because poverty in rural and urban areas of th...
124,spatial determinants of poverty using gis-base...,WoB,NaN,NaN

In [50]:
dropduplicat.to_csv('proce_data/removed_duplicat.csv', index=False)

In [3]:
list_clean_articles = pd.read_excel('proce_data/list_of_articles.xlsx')

In [5]:
list_clean_articles_frther = list_clean_articles[list_clean_articles['status'] == 'Y']

In [7]:
filtered_article = list_clean_articles[list_clean_articles['status'] == 'N']

In [8]:
filtered_article

,Title,Source,Link,Abstract,status
1,"automation, ai, and the global future of work:...",Scopus,https://www.scopus.com/pages/publications/1050...,Automation and artificial intelligence (AI) ar...,N
2,coding and capability-building in nonprofit di...,Scopus,https://www.scopus.com/pages/publications/8519...,Digital journalism scholars highlighted a gap ...,N
3,intelligent future or neo-colonialism?,Scopus,https://www.scopus.com/pages/publications/1050...,This is a commentary on the current fervour ab...,N
4,flood-tech frontiers: smart but just? a system...,Scopus,https://www.scopus.com/pages/publications/1050...,"As rising waters meet rising technologies, a n...",N
5,paradigms and platforms: artificial intelligen...,Scopus,https://www.scopus.com/pages/publications/1050...,This chapter explores how AI‚Äîespecially larg...,N
...,...,...,...,...,...
1237,"gis, spatial analysis and spatial statistics",WoB,NaN,NaN,N
1238,measuring equity through spatial variability o...,WoB,NaN,Recent regional research has taken an 'infrast...,N
1239,gis and spatial statistics/econometrics: an ov...,WoB,NaN,NaN,N
1240,spatial variations in us poverty: beyond metro...,WoB,NaN,Because poverty in rural and urban areas of th...,N
1241,spatial determinants of poverty using gis-base...,WoB,NaN,NaN,N

In [6]:
list_clean_articles_frther

,Title,Source,Link,Abstract,status
0,algorithmic climate justice: how ai bias exace...,Scopus,https://www.scopus.com/pages/publications/1050...,This chapter explores how algorithmic biases i...,Y
6,digital exclusion and inequality: mapping divi...,Scopus,https://www.scopus.com/pages/publications/1050...,"The access to education, employment, health ca...",Y
9,digital divide,Scopus,https://www.scopus.com/pages/publications/1050...,The Digital Divide is a concept that was origi...,Y
10,a review of literature on information poverty,Scopus,https://www.scopus.com/pages/publications/8516...,The Data Poverty Index (DPI) highlights the pr...,Y
18,volunteer geographic information in the global...,Scopus,https://www.scopus.com/pages/publications/8508...,The world is awash in data‚Äîby 2020 it is exp...,Y
...,...,...,...,...,...
1210,"dazzled by data: big data, the census and urba...",WoB,NaN,NaN,Y
1211,issues in spatial data analysis,WoB,NaN,Misspecified functional forms tend to produce ...,Y
1214,transition to the new normal: lens on the urba...,WoB,NaN,NaN,Y
1216,reconsidering the definition of a spatial data...,WoB,NaN,The great interest in spatial data infrastruct...,Y
1218,"geography, spatial data analysis, and geostati...",WoB,NaN,Geostatistics is a distinctive methodology wit...,Y

In [24]:
df_wob_type = df_wob_type[df_wob_type['Document Type'] == 'Article']

In [27]:
df_wob_type_title = list(df_wob_type['Article Title'].astype(str).str.lower())

In [28]:
further_filter_title = list(further_filter['Title'].astype(str).str.lower())

In [33]:
googlelist = list(google_sch['Title'].astype(str).str.lower())

In [34]:
full_title = df_wob_type_title+further_filter_title+googlelist

In [35]:
peer_reviewlist = list_clean_articles_frther[list_clean_articles_frther['Title'].isin(full_title)]

In [ ]:
#list_clean_articles_frther.to_excel('proce_data/articles_review_abst.xlsx')

In [36]:
peer_reviewlist

,Title,Source,Link,Abstract,status
9,digital divide,Scopus,https://www.scopus.com/pages/publications/1050...,The Digital Divide is a concept that was origi...,Y
18,volunteer geographic information in the global...,Scopus,https://www.scopus.com/pages/publications/8508...,The world is awash in data‚Äîby 2020 it is exp...,Y
21,"digital colonialism, ecological crisis and the...",Scopus,https://www.scopus.com/pages/publications/1050...,This article examines the intertwined dynamics...,Y
25,addressing the information deficit in global h...,Scopus,https://www.scopus.com/pages/publications/8506...,Lack of investment in low-income and middle-in...,Y
32,artificial intelligence for social innovation:...,Scopus,https://www.scopus.com/pages/publications/8520...,"In an era of rapid technological advancement, ...",Y
...,...,...,...,...,...
1190,geographic data science,WoB,NaN,It is widely acknowledged that the emergence o...,Y
1201,a novel method for socioeconomic data spatiali...,WoB,NaN,Detailed spatial representation of socioeconom...,Y
1208,strategies to access web-enabled urban spatial...,WoB,NaN,Since the introduction of the World Wide Web i...,Y
1211,issues in spatial data analysis,WoB,NaN,Misspecified functional forms tend to produce ...,Y
1216,reconsidering the definition of a spatial data...,WoB,NaN,The great interest in spatial data infrastruct...,Y

In [38]:
peer_reviewlist.to_excel('proce_data/peer_reviewedarticles.xlsx', index=False)

In [2]:
proces_data = pd.read_excel('proce_data/peer_reviewedarticles.xlsx')

In [3]:
set(proces_data['Abstract_status'].to_list())

{'Likely ', 'May be', 'May be ', 'No', 'Y'}

In [4]:
proces_data['Abstract_status'] = proces_data['Abstract_status'].apply(lambda x: 'May be' if x == 'May be ' else x)

In [5]:
set(proces_data['Abstract_status'].to_list())

{'Likely ', 'May be', 'No', 'Y'}

In [6]:
newdata_sources = proces_data[proces_data['Abstract_status'].isin(['Y'])]

In [7]:
newdata_sources.to_excel('proce_data/yes_articles_furtherreview.xlsx', index=False)

In [8]:
maybarticles = proces_data[proces_data['Abstract_status'].isin(['May be', 'Likely'])]

In [9]:
maybarticles.to_excel('proce_data/maybearticles.xlsx', index=False)